### PR TITLE
feat: remove ink recognition support in the foss flavor

### PR DESCRIPTION
**Pull request by proletarius101**
The ink recognition feature requires proprietary GMS to be included

### CODE REVIEW

**Comment by AlienKevin** [comment]
@proletarius101 Could you submit a PR to merge into the fdroid branch instead? I still want to keep the ink recognition feature for main.

**Comment by proletarius101** [comment]
> @proletarius101 Could you submit a PR to merge into the fdroid branch instead? I still want to keep the ink recognition feature for main.

There might be a bug in the build script. But this PR aims to remove the ink recognition feature **only** in the foss build variant. Does that work for you?

**Comment by AlienKevin** [comment]
@proletarius101 That works and thanks for adding an explanation message for the missing feature!

**Comment by proletarius101** [comment]
Hmm... Unfortunately, it [doesn't work](https://gitlab.com/fdroid/fdroiddata/-/jobs/6797893810)... Let me see what else I can do

**Comment by AlienKevin** [comment]
@proletarius101 I found and fixed a typo in `digital_ink_view.dart`. I think you were using `fdroid` as the appFlavor name but it should be `foss`.

**Pull request merged**
